language: objective-c
osx_image: xcode8.2
before_install:
  - brew update
  - brew install libscrypt
  - brew install prashnts/zen/libed25519
  - gem install xcpretty xcpretty-travis-formatter
script:
  - xcodebuild -workspace kbswift.xcworkspace -scheme kbswift test | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email: false
